name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Lexic:
    name: Lexic Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Compile the tests
      run: |
        cd Lexic/test/_build/
        make
        
    - name: Run tests
      run: |
        cd Lexic/test/_build/
        ./test_all
